### ISSUE TITLE
[Enhancement]  Please consider to add VCAP_APPLICATION to copy

### ISSUE THREAD

**Issue by ibmamnt** [jthomas/copyenv#1]
Hi,

I'm using this plugin. This is not an actual issue, but rather enhancement to include VCAP_APPLICATION variable.  I'm developing some flows in Node-RED from IBM Bluemix. In this template, it is expected to use VCAP_APPLICATION as well as VCAP_SERVICES. Node-RED boilerplate's setting.js (bluemix-setting.js) requires both variable like:

```
var VCAP_APPLICATION = JSON.parse(process.env.VCAP_APPLICATION);
var VCAP_SERVICES = JSON.parse(process.env.VCAP_SERVICES);
```

So if this utility can copy the VCAP_APPLICATION too, this is more helpful to debug Node-RED flow locally. 

Thanks !

**Comment by jthomas** [comment]
This is a good idea, will work on this.

**Comment by jthomas** [comment]
I've merged to a PR to do this.

**Comment by ibmamnt** [comment]
Nice !
