### ISSUE TITLE
"missing service credentials for application"

### ISSUE THREAD

**Issue by afeld** [jthomas/copyenv#2]

**Comment by afeld** [comment]
Oops, submitted too early. `cf env` runs fine, but I run into the error above when running `cf copyenv`:

```
$ cf --version
cf version 6.12.4-b4b6af1-2015-09-18T17:54:54+00:00
$ cf env slackin
Getting env variables for app slackin in org 18f / space chat as aidan.feldman@gsa.gov...
OK

System-Provided:


{
 "VCAP_APPLICATION": {
  ...
 }
}

User-Provided:
...

No running env variables have been set

No staging env variables have been set

$ cf copyenv slackin
error:  missing service credentials for application
```

I don't really know Go, but is it possible that the plugin breaks if you don't have any services attached to an application?

**Comment by jthomas** [comment]
I think it does.
Can I ask what you're hoping to achieve with the "copyenv" plugin if you don't have service credentials bound to your application?

**Comment by afeld** [comment]
I have User-Provided environment variables (questionable, I know), so was just hoping to grab those.

**Comment by jthomas** [comment]
The plugin doesn't currently support exporting anything but the VCAP_SERVICES credentials. 
I have another issue (#1) open for adding support for VCAP_APPLICATION. I'll look at adding this feature in when I fix that bug...

**Comment by jthomas** [comment]
I've merged a PR to add this feature.
