### ISSUE TITLE
Error executing cli core command

### ISSUE THREAD

**Issue by lmsurprenant** [jthomas/copyenv#3]
~~Tried out this plugin today and I think it needs updating.~~

I retract my previous statement.  The problem is that I had the name of the app wrong.  Would be nice to print a clearer message saying an application with this name doesn't exist.  Nice plugin.

**Comment by jthomas** [comment]
Aha - thanks for letting me know, I'll add that.

**Comment by jthomas** [comment]
Added a better error message for this.
