### ISSUE TITLE
Move RetrieveAppNameEnv and ExtractCredentialsJSON and others to non main package

### ISSUE THREAD

**Issue by jcscottiii** [jthomas/copyenv#7]
As an third party app developer, I would love to just import some of this logic but right I can cant since it's in the main package.

The logic that gets the VCAP_SERVICES and other env vars could be re-used for other plugins

**Comment by jthomas** [comment]
Hello James, this sounds like a good idea. 

My Go language skills are pretty weak though and I'm not sure exactly how to re-work the project to support this. I do not have time to work on this at the moment.

Would you be able to submit a PR with these changes to the project? 

Assuming the tests still pass, it should be a simple merge.
