### ISSUE TITLE
Get fatal error on Mac OS High Sierra

### ISSUE THREAD

**Issue by datenengel** [jthomas/copyenv#8]
After updating to high sierra, I got 

failed MSpanList_Insert 0x617000 0x476f552a5f10 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x55930b)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/panic.go:491 +0xad fp=0x7ffeefbfe030 sp=0x7ffeefbfe000
runtime.MSpanList_Insert(0x5827a8, 0x617000)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:692 +0x8f fp=0x7ffeefbfe058 sp=0x7ffeefbfe030
MHeap_FreeSpanLocked(0x57f3a0, 0x617000, 0x100)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:583 +0x163 fp=0x7ffeefbfe098 sp=0x7ffeefbfe058
MHeap_Grow(0x57f3a0, 0x8, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:420 +0x1a8 fp=0x7ffeefbfe0d8 sp=0x7ffeefbfe098
MHeap_AllocSpanLocked(0x57f3a0, 0x1, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:298 +0x365 fp=0x7ffeefbfe118 sp=0x7ffeefbfe0d8
mheap_alloc(0x57f3a0, 0x1, 0x12, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:190 +0x121 fp=0x7ffeefbfe140 sp=0x7ffeefbfe118
runtime.MHeap_Alloc(0x57f3a0, 0x1, 0x10000000012, 0xf619)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/mheap.c:240 +0x66 fp=0x7ffeefbfe178 sp=0x7ffeefbfe140
MCentral_Grow(0x587118, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcentral.c:197 +0x8b fp=0x7ffeefbfe1e0 sp=0x7ffeefbfe178
runtime.MCentral_CacheSpan(0x587118, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcentral.c:85 +0x167 fp=0x7ffeefbfe218 sp=0x7ffeefbfe1e0
runtime.MCache_Refill(0x613000, 0x12, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/mcache.c:90 +0xa0 fp=0x7ffeefbfe240 sp=0x7ffeefbfe218
runtime.mcacheRefill_m()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.c:368 +0x57 fp=0x7ffeefbfe260 sp=0x7ffeefbfe240
runtime.onM(0x44dc98)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:273 +0x9a fp=0x7ffeefbfe268 sp=0x7ffeefbfe260
runtime.mallocgc(0x120, 0x37b160, 0x0, 0x0)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:178 +0x849 fp=0x7ffeefbfe318 sp=0x7ffeefbfe268
runtime.newobject(0x37b160, 0x613000)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/malloc.go:353 +0x49 fp=0x7ffeefbfe340 sp=0x7ffeefbfe318
runtime.newG(0x28c7a)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.go:233 +0x2a fp=0x7ffeefbfe358 sp=0x7ffeefbfe340
allocg(0x56f820)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:925 +0x1f fp=0x7ffeefbfe368 sp=0x7ffeefbfe358
runtime.malg(0x8000, 0x56fc60)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:2106 +0x1f fp=0x7ffeefbfe398 sp=0x7ffeefbfe368
runtime.mpreinit(0x570280)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/os_darwin.c:137 +0x27 fp=0x7ffeefbfe3b0 sp=0x7ffeefbfe398
mcommoninit(0x570280)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:201 +0xc9 fp=0x7ffeefbfe3d8 sp=0x7ffeefbfe3b0
runtime.schedinit()
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/proc.c:138 +0x55 fp=0x7ffeefbfe400 sp=0x7ffeefbfe3d8
runtime.rt0_go(0x7ffeefbfe438, 0x4, 0x7ffeefbfe438, 0x0, 0x0, 0x4, 0x7ffeefbfe670, 0x7ffeefbfe693, 0x7ffeefbfe699, 0x7ffeefbfe6a1, ...)
        /usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:95 +0x116 fp=0x7ffeefbfe408 sp=0x7ffeefbfe400

seems to me that the binaries must be rebuild with a current go library for high sierra.

**Comment by datenengel** [comment]
cf cli version 6.32.0+0191c33d9.2017-09-26

**Comment by jthomas** [comment]
Hello. I'm not actively using or maintainer this project anymore 😢. If you want to submit a PR to resolve the bug I will happily merge?

**Comment by datenengel** [comment]
solved
